# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 08:34
from __future__ import unicode_literals

from django.db import migrations
import submission.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcomponent',
            name='max_size',
            field=submission.models.base.FileSizeField(default=10, help_text=b'Maximum length, in kB.'),
        ),
    ]
