# Generated by Django 2.2.15 on 2021-04-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='thread_type',
            field=models.CharField(choices=[('DFT', 'Default'), ('QUT', 'Question')], default='DFT', help_text='The thread types: Default: No additional behaviour, Question: Request an instructor answer', max_length=3),
        ),
    ]
