# Generated by Django 2.2.15 on 2021-04-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumthread_thread_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='endorsed_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.ForumReply'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='endorsed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsed_by', to='coredata.Member'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='endorsed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='coredata.Member'),
        ),
    ]
