# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('content_hash', models.CharField(max_length=128)),
                ('filepath', models.CharField(max_length=500, null=True)),
                ('size', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('storage_id', models.CharField(db_index=True, max_length=32)),
                ('filedata', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hybrid_storage.FileData')),
            ],
        ),
        migrations.CreateModel(
            name='FileWrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('fileinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hybrid_storage.FileInfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='filewrite',
            unique_together=set([('fileinfo', 'location')]),
        ),
    ]
