# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 08:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_autoslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='svn_slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=17, null=True, populate_from=b'slug', unique_with=(b'courseoffering',)),
        ),
    ]
